### ISSUE TITLE
Problem when using `loaders`

### ISSUE THREAD

**Issue by ratson** [lewie9021/webpack-configurator#1]
According to [webpack documentation](http://webpack.github.io/docs/using-loaders.html), `module.loaders[].loaders` is a valid for the config.
But when it is used, `resolve()` produce both `loaders` and `loader`, which cause problems.

I have written a simple demo to the problem, please see https://github.com/ratson/webpack-configurator/commit/4b7227926a798321b9058df76106e33f3c6b081d

**Comment by lewie9021** [comment]
Thanks for find this bug. I've been meaning to write some tests for this module for quite some time. I believe the referenced commit has fixed the issue you're having and will be in the next version.
