### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by LukeSheard** [lewie9021/webpack-configurator#16]
Is this project still being maintained? I would like to see support for webpack2 with that releasing coming up and I've been using this module which has a strict dependency here: https://www.npmjs.com/package/webpack-multi-configurator. 

Would be good to hear what's going on since the 1.0.0 has been 'coming in the next few weeks' for a couple of months now. Thanks!

**Comment by lee-houghton** [comment]
11 months, to be exact! 

I'm interested in knowing what doesn't work for you with webpack 2. I've even been using 0.1.0 with webpack 2 with no problems.

**Comment by LukeSheard** [comment]
@lee-houghton I actually can't remember, I think it was to do with Rules / Loaders with queries for each loader using the new syntax. I ended up moving to npm.im/webpack-merge on the recommendation of some webpack contributors.

**Comment by LukeSheard** [comment]
Closing because the new versions of Webpack have better utilities for this now and I no longer need this issue.
